### ISSUE TITLE
Wallet crashes on launch with SIGSEGV (Segmentation Fault)

### ISSUE THREAD

**Issue by Fractalguise** [RavenProject/Ravencoin#108]
### Describe the issue
Wallet crashes on launch.

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. ./raven-qt

### Expected behaviour
I expect the wallet to launch without error.

### Actual behaviour
Wallet crashes with this message of Segmentation fault.    

### Machine specs:
OS: Arch Linux x86_64
Kernel: 4.17.3-1-ARCH
RAM: 1568M / 3787M (41%)
CPU: Intel(R) Pentium(R) CPU N4200 @ 1.10GHz
HDD: 54G

### Any extra information that might be useful in the debugging process.

I followed the GDB arch wiki pages as best I could:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./raven-qt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f59f2e551e6 in __strlen_sse2 () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f59df0d5700 (LWP 12754))]
(gdb) bt

#0  0x00007f59f2e551e6 in __strlen_sse2 () from /usr/lib/libc.so.6
#1  0x00007f59f472e7b3 in __os_strdup () from /usr/lib/libdb_cxx-4.8.so
#2  0x00007f59f4701975 in __env_add_data_dir () from /usr/lib/libdb_cxx-4.8.so
#3  0x00007f59f4701a42 in __env_set_data_dir () from /usr/lib/libdb_cxx-4.8.so
#4  0x00007f59f46208e9 in DbEnv::set_data_dir(char const*) () from /usr/lib/libdb_cxx-4.8.so
#5  0x00005644b5d66138 in CDBEnv::Open(boost::filesystem::path const&) ()
#6  0x00005644b5d68150 in CDB::VerifyEnvironment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#7  0x00005644b5d4f2bc in CWalletDB::VerifyEnvironment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#8  0x00005644b5ca8777 in VerifyWallets() ()
#9  0x00005644b591ba83 in AppInitMain(boost::thread_group&, CScheduler&) ()
#10 0x00005644b5700ab6 in RavenCore::initialize() ()
#11 0x00005644b56ffd8e in RavenCore::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#12 0x00007f59f53243d2 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#13 0x00007f59f62fda74 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007f59f6305341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007f59f52f9cb9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#16 0x00007f59f52fcd4c in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#17 0x00007f59f534da54 in ?? () from /usr/lib/libQt5Core.so.5
#18 0x00007f59f06fd368 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#19 0x00007f59f06fd5b1 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007f59f06fd63e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#21 0x00007f59f534d039 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007f59f52f894c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#23 0x00007f59f5141a99 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#24 0x00007f59f514bb45 in ?? () from /usr/lib/libQt5Core.so.5
#25 0x00007f59f498f075 in start_thread () from /usr/lib/libpthread.so.0
#26 0x00007f59f2eb653f in clone () from /usr/lib/libc.so.6

(gdb) r
Starting program: /home/fractalsguise/RVN/Ravencoin/src/qt/raven-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe958a700 (LWP 15716)]
qt5ct: using qt5ct plugin
[New Thread 0x7fffe03ad700 (LWP 15717)]
[New Thread 0x7fffdfbac700 (LWP 15718)]
[New Thread 0x7fffdf3ab700 (LWP 15719)]
[New Thread 0x7fffdcb12700 (LWP 15720)]
[New Thread 0x7fffcffff700 (LWP 15721)]
[New Thread 0x7fffcf7fe700 (LWP 15722)]
[New Thread 0x7fffceffd700 (LWP 15723)]

Thread 5 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdf3ab700 (LWP 15719)]
0x00007ffff311f1e6 in __strlen_sse2 () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff311f1e6 in __strlen_sse2 () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff49f87b3 in __os_strdup () from /usr/lib/libdb_cxx-4.8.so
No symbol table info available.
#2  0x00007ffff49cb975 in __env_add_data_dir () from /usr/lib/libdb_cxx-4.8.so
No symbol table info available.
#3  0x00007ffff49cba42 in __env_set_data_dir () from /usr/lib/libdb_cxx-4.8.so
No symbol table info available.
#4  0x00007ffff48ea8e9 in DbEnv::set_data_dir(char const*) () from /usr/lib/libdb_cxx-4.8.so
No symbol table info available.
#5  0x0000555555c26138 in CDBEnv::Open(boost::filesystem::path const&) ()
No symbol table info available.
#6  0x0000555555c28150 in CDB::VerifyEnvironment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
No symbol table info available.
#7  0x0000555555c0f2bc in CWalletDB::VerifyEnvironment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
No symbol table info available.
#8  0x0000555555b68777 in VerifyWallets() ()
No symbol table info available.
#9  0x00005555557dba83 in AppInitMain(boost::thread_group&, CScheduler&) ()
No symbol table info available.
#10 0x00005555555c0ab6 in RavenCore::initialize() ()
No symbol table info available.
#11 0x00005555555bfd8e in RavenCore::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
No symbol table info available.
#12 0x00007ffff55ee3d2 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#13 0x00007ffff65c7a74 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#14 0x00007ffff65cf341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#15 0x00007ffff55c3cb9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#16 0x00007ffff55c6d4c in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/libQt5Core.so.5
No symbol table info available.
#17 0x00007ffff5617a54 in ?? () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#18 0x00007ffff09c7368 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#19 0x00007ffff09c75b1 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#20 0x00007ffff09c763e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#21 0x00007ffff5617039 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
No symbol table info available.
#22 0x00007ffff55c294c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
No symbol table info available.
#23 0x00007ffff540ba99 in QThread::exec() () from /usr/lib/libQt5Core.so.5
No symbol table info available.

**Comment by Fractalguise** [comment]
I found my issue. I had Berkeley DB 4.8 and 5.3 installed while musing --with-incompatible-bdb. This let the wallet be compiled and launch then immediately crash.
